[package]
name = "macros"
version = "0.1.0"
edition = "2024"
authors = ["Kirill Udaltsov <commits@udaltsovk.ru>"]

[dependencies]
async-trait.workspace = true
paste.workspace = true
stringcase.workspace = true
