[package]
name = "macros"
version = "0.1.0"
authors = ["Kirill Udaltsov <commits@udaltsovk.ru>"]
license.workspace = true
edition.workspace = true

[features]
surrealdb = ["dep:surrealdb"]

[dependencies]
async-trait = "0.1"
paste = "1.0"

surrealdb = { workspace = true, optional = true }
