[package]
name = "macros"
version = "0.1.0"
edition = "2024"
authors = ["Kirill Udaltsov <commits@udaltsovk.ru>"]

[features]
default = ["surrealdb"]

[dependencies]
async-trait = "0.1"
paste = "1.0"
stringcase = "0.4"

surrealdb = { workspace = true, optional = true }
