name: minizord-dev-frontend
services:
  db:
    image: surrealdb/surrealdb:latest
    restart: on-failure
    user: root
    volumes:
      - db:/var/lib/surrealdb
    command:
      - start
    environment:
      SURREAL_USER: root
      SURREAL_PASS: root
      SURREAL_PATH: rocksdb:/var/lib/surrealdb

  s3:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - s3:/data
    command: server /data --console-address ":9001"

  init-buckets:
    image: minio/mc:latest
    depends_on:
      - s3
    entrypoint: >
      sh -c "until mc alias set myminio http://s3:9000 minioadmin minioadmin; do sleep 1; done &&
             mc mb myminio/loki &&
             mc mb myminio/tempo &&
             mc mb myminio/mimir &&
             mc mb myminio/images &&
             mc policy set public myminio/loki"
  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana:/var/lib/grafana

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - prometheus:/prometheus
      - ../assets/configs/dev/prometheus-dev.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--enable-feature=native-histograms"
      - "--web.listen-address=:9091"

  loki:
    image: grafana/loki:latest
    restart: always
    volumes:
      - ../assets/configs/dev/loki.yml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    depends_on:
      - s3

  tempo:
    image: grafana/tempo:latest
    restart: always
    volumes:
      - ../assets/configs/dev/tempo.yml:/etc/tempo/tempo-config.yaml
      - tempo:/var/tempo
    command: -config.file=/etc/tempo/tempo-config.yaml
    depends_on:
      - s3
      - prometheus

  mimir:
    image: grafana/mimir:latest
    restart: always
    volumes:
      - ../assets/configs/dev/mimir.yml:/etc/mimir/mimir.yaml
    command: --config.file=/etc/mimir/mimir.yaml
    depends_on:
      - s3

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - ../assets/configs/dev/otel-collector.yml:/etc/otelcol-contrib/config.yaml

  api:
    image: ghcr.io/udaltsovk/minizord-api:master
    restart: on-failure
    depends_on:
      - db
      - s3
      - otel-collector
    environment:
      RUST_LOG: debug
      SERVER_ADDRESS: 0.0.0.0:8080
      DB_ADDRESS: db:8000
      DB_NAMESPACE: minizord
      DB_NAME: api
      DB_USER: root
      DB_PASSWORD: root
      OTEL_ENDPOINT: http://otel-collector:4317
      OTEL_SERVICE_NAME: minizord_api
      S3_BASE_URL: http://s3:9000
      S3_ACCESS_KEY: minioadmin
      S3_SECRET_KEY: minioadmin
      S3_REGION: custom
    ports:
      - "8080:8080"
volumes:
  db:
  s3:
  prometheus:
  tempo:
  grafana:
