[workspace]
resolver = "2"
members = [ 
    "crates/macros",
    "crates/utils",  
    "crates/repository",
    "crates/dto",
    "crates/service",
    "crates/handler", 
    "crates/app",
]

[workspace.dependencies]
macros.path = "./crates/macros"
utils.path = "./crates/utils"
dto.path = "./crates/dto"

env-vars-config = "0.1"

async-trait = "0.1"
paste = "1.0"
stringcase = "0.4"

log = "0.4"
env_logger = "0.11"
thiserror = "2.0"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
validator = { version = "0.20", features = ["derive"] }
ulid = { version = "1.2", features = ["serde"] }

utoipa = { version = "5.3", features = ["actix_extras", "ulid"] }
utoipa-actix-web = "0.1"

