[workspace]
resolver = "2"
members = [ 
    "crates/macros",
    "crates/utils",  
    "crates/api/repository",
    "crates/api/dto",
    "crates/api/service",
    "crates/api/handler", 
    "crates/api", 
    "crates/mail", 
    "crates/telegram", 
    "crates/testing/repository",
    "crates/testing/service", 
    "crates/testing/handler", 
    "crates/testing/api", 
    "crates/testing/mail", 
    "crates/testing/telegram",
]

[workspace.dependencies]
macros.path = "./crates/macros"
utils.path = "./crates/utils"
dto.path = "./crates/api/dto"

env-vars-config = "0.2"

log = "0.4"
env_logger = "0.11"
thiserror = "2.0"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
validator = { version = "0.20", features = ["derive"] }
ulid = { version = "1.2", features = ["serde"] }

utoipa = { version = "5.3", features = ["actix_extras", "ulid", "preserve_order", "preserve_path_order"] }

actix-web = "4.10"
actix-web-lab = "0.23"
utoipa-actix-web = "0.1"

