{
 "title": "HAProxy",
 "description": "HAProxy with Prometheus data",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "backend",
    "label": "Backend",
    "query": {
     "query": "label_values(haproxy_backend_status{instance=\"proxy:8080\"}, proxy)"
    }
   },
   {
    "name": "frontend",
    "label": "Frontend",
    "query": {
     "query": "label_values(haproxy_frontend_status{instance=\"proxy:8080\"}, proxy)"
    }
   },
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "label_values(haproxy_server_status{instance=\"proxy:8080\"}, server)"
    }
   },
   {
    "name": "code",
    "label": "HTTP Code",
    "query": {
     "query": "label_values(haproxy_server_http_responses_total{instance=\"proxy:8080\"}, code)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Basic General Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "All HTTP responses",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(haproxy_frontend_http_responses_total{proxy=~\"$frontend\",code=~\"$code\",instance=\"proxy:8080\"}[$__rate_interval])) by (code)",
     "legendFormat": "Front {{ code }}"
    },
    {
     "expr": "sum(rate(haproxy_backend_http_responses_total{proxy=~\"$backend\",code=~\"$code\",instance=\"proxy:8080\"}[$__rate_interval])) by (code)",
     "legendFormat": "Back {{ code }}"
    }
   ]
  },
  {
   "title": "Incoming / Outgoing bytes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "sum(rate(haproxy_frontend_bytes_in_total{proxy=~\"$frontend\",instance=\"proxy:8080\"}[$__rate_interval])*8) by (instance)",
     "legendFormat": "IN Front"
    },
    {
     "expr": "sum(rate(haproxy_frontend_bytes_out_total{proxy=~\"$frontend\",instance=\"proxy:8080\"}[$__rate_interval])*8) by (instance)",
     "legendFormat": "OUT Front"
    },
    {
     "expr": "sum(rate(haproxy_backend_bytes_in_total{proxy=~\"$backend\",instance=\"proxy:8080\"}[$__rate_interval])*8) by (instance)",
     "legendFormat": "IN Back"
    },
    {
     "expr": "sum(rate(haproxy_backend_bytes_out_total{proxy=~\"$backend\",instance=\"proxy:8080\"}[$__rate_interval])*8) by (instance)",
     "legendFormat": "OUT Back"
    }
   ]
  },
  {
   "title": "Number of connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(haproxy_frontend_connections_total{proxy=~\"$frontend\",instance=\"proxy:8080\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Front"
    },
    {
     "expr": "sum(rate(haproxy_backend_connection_errors_total{proxy=~\"$backend\",instance=\"proxy:8080\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Back errors"
    }
   ]
  },
  {
   "title": "Requests and Responses",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(haproxy_frontend_http_requests_total{proxy=~\"$frontend\",instance=\"proxy:8080\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Front requests"
    },
    {
     "expr": "sum(rate(haproxy_frontend_request_errors_total{proxy=~\"$frontend\",instance=\"proxy:8080\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Front requests errors"
    },
    {
     "expr": "sum(rate(haproxy_frontend_requests_denied_total{proxy=~\"$frontend\",instance=\"proxy:8080\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Front request denied"
    },
    {
     "expr": "sum(rate(haproxy_backend_redispatch_warnings_total{proxy=~\"$backend\",instance=\"proxy:8080\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Back redispatch warnings"
    },
    {
     "expr": "sum(rate(haproxy_backend_retry_warnings_total{proxy=~\"$backend\",instance=\"proxy:8080\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Back retry warnings"
    },
    {
     "expr": "sum(rate(haproxy_backend_response_errors_total{proxy=~\"$backend\",instance=\"proxy:8080\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Back response errors"
    },
    {
     "expr": "sum(haproxy_backend_current_queue{proxy=~\"$backend\",instance=\"proxy:8080\"}) by (instance)",
     "legendFormat": "Back queued requests"
    },
    {
     "expr": "sum(rate(haproxy_backend_http_requests_total{proxy=~\"$backend\",instance=\"proxy:8080\"}[$__rate_interval])) by (instance)",
     "legendFormat": "Back requests"
    }
   ]
  },
  {
   "title": "Active sessions",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(haproxy_frontend_current_sessions{proxy=~\"$frontend\",instance=\"proxy:8080\"}) by (instance)",
     "legendFormat": "Front"
    },
    {
     "expr": "sum(haproxy_backend_current_sessions{proxy=~\"$frontend\",instance=\"proxy:8080\"}) by (instance)",
     "legendFormat": "Back"
    }
   ]
  },
  { "title": "Basic General Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "All Status",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 22, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(haproxy_frontend_status{instance=\"proxy:8080\"} == 1)",
     "legendFormat": "Front Up"
    },
    {
     "expr": "count(haproxy_backend_status{instance=\"proxy:8080\"} ==1)",
     "legendFormat": "Back Up"
    }
   ]
  },
  {
   "title": "Started...",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - haproxy_process_start_time_seconds{instance=\"proxy:8080\"}"
    }
   ]
  },
  {
   "title": "Throughtput / Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Front - Incoming / Outgoing bytes",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 105 },
     "fieldConfig": { "defaults": { "unit": "bits" } },
     "targets": [
      {
       "expr": "rate(haproxy_frontend_bytes_in_total{proxy=~\"$frontend\",instance=\"proxy:8080\"}[$__rate_interval])*8",
       "legendFormat": "IN {{ proxy }}"
      },
      {
       "expr": "rate(haproxy_frontend_bytes_out_total{proxy=~\"$frontend\",instance=\"proxy:8080\"}[$__rate_interval])*8",
       "legendFormat": "OUT {{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Incoming / Outgoing bytes",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 12, "y": 105 },
     "fieldConfig": { "defaults": { "unit": "bits" } },
     "targets": [
      {
       "expr": "rate(haproxy_backend_bytes_in_total{proxy=~\"$backend\",instance=\"proxy:8080\"}[$__rate_interval])*8",
       "legendFormat": "IN {{ proxy }}"
      },
      {
       "expr": "rate(haproxy_backend_bytes_out_total{proxy=~\"$backend\",instance=\"proxy:8080\"}[$__rate_interval])*8",
       "legendFormat": "OUT {{ proxy }}"
      }
     ]
    },
    {
     "title": "Front - Connections successful / denied",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 120 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_frontend_connections_total{proxy=~\"$frontend\",instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "Successful {{ proxy }}"
      },
      {
       "expr": "rate(haproxy_frontend_denied_connections_total{proxy=~\"$frontend\",instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "Denied {{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Connections attempts / errors",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 12, "y": 120 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_backend_connection_attempts_total{proxy=~\"$backend\",instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "Attempts {{ proxy }}"
      },
      {
       "expr": "rate(haproxy_backend_connection_errors_total{proxy=~\"$backend\",instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "Error {{ proxy }}"
      }
     ]
    },
    {
     "title": "Front - Maximum observed number of connections per second",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 135 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_frontend_connections_rate_max{proxy=~\"$frontend\",instance=\"proxy:8080\"}",
       "legendFormat": "Max {{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Connections reuses",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 12, "y": 135 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_backend_connection_reuses_total{proxy=~\"$backend\",instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "Reuses {{ proxy }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Queues",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Back - Queued requests not assigned to any server",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 106 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_backend_current_queue{proxy=~\"$backend\",instance=\"proxy:8080\"}",
       "legendFormat": "Queued {{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Max queued requests not assigned to any server",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 106 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_backend_max_queue{proxy=~\"$backend\",instance=\"proxy:8080\"}",
       "legendFormat": "Max {{ proxy }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Requests / Responses",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Back - HTTP requests OK / Denied",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 107 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_backend_http_requests_total{proxy=~\"$backend\",instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "Total {{ proxy }}"
      },
      {
       "expr": "rate(haproxy_backend_requests_denied_total{proxy=~\"$backend\", instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "Denied {{ proxy }}"
      }
     ]
    },
    {
     "title": "Front - HTTP requests OK / Error / Denied",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 107 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_frontend_http_requests_total{proxy=~\"$frontend\",instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "Total {{ proxy }}"
      },
      {
       "expr": "rate(haproxy_frontend_request_errors_total{proxy=~\"$frontend\", instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "Error {{ proxy }}"
      },
      {
       "expr": "rate(haproxy_frontend_requests_denied_total{proxy=~\"$frontend\", instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "Denied {{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - HTTP responses denied",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 121 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_backend_responses_denied_total{proxy=~\"$backend\", instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "Denied {{ proxy }}"
      }
     ]
    },
    {
     "title": "Front - HTTP responses denied",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 121 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_frontend_responses_denied_total{proxy=~\"$frontend\",instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "Denied {{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Error / Redispatch / Retry",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 135 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_backend_redispatch_warnings_total{proxy=~\"$backend\", instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "Redispatch {{ proxy }}"
      },
      {
       "expr": "rate(haproxy_backend_retry_warnings_total{proxy=~\"$backend\", instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "Retry {{ proxy }}"
      },
      {
       "expr": "rate(haproxy_backend_response_errors_total{proxy=~\"$backend\", instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "Error {{ proxy }}"
      }
     ]
    },
    {
     "title": "Front - Maximum observed number of HTTP requests per second",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 135 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_frontend_http_requests_rate_max{proxy=~\"$frontend\", instance=\"proxy:8080\"}",
       "legendFormat": "Max {{ proxy }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Times",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Back - Avg connection time",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 108 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "haproxy_backend_connect_time_average_seconds{proxy=~\"$backend\",instance=\"proxy:8080\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Max connection time",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 108 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "haproxy_backend_max_connect_time_seconds{proxy=~\"$backend\",instance=\"proxy:8080\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Avg. total time",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 122 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "haproxy_backend_total_time_average_seconds{proxy=~\"$backend\",instance=\"proxy:8080\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Max total time",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 122 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "haproxy_backend_max_total_time_seconds{proxy=~\"$backend\",instance=\"proxy:8080\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Avg. response time",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 136 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "haproxy_backend_response_time_average_seconds{proxy=~\"$backend\",instance=\"proxy:8080\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Max response time",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 136 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "haproxy_backend_max_response_time_seconds{proxy=~\"$backend\",instance=\"proxy:8080\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Avg. queue time for last 1024 successful connections",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 150 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "haproxy_backend_queue_time_average_seconds{proxy=~\"$backend\",instance=\"proxy:8080\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Max queue time",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 150 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "haproxy_backend_max_queue_time_seconds{proxy=~\"$backend\",instance=\"proxy:8080\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Responses by HTTP code",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Front - HTTP responses code",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 109 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_frontend_http_responses_total{proxy=~\"$frontend\", code=~\"$code\",instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "{{ code }} {{ proxy }} "
      }
     ]
    },
    {
     "title": "Back - HTTP responses code",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 109 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_backend_http_responses_total{proxy=~\"$backend\", code=~\"$code\",instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "{{ code }} {{ proxy }}"
      }
     ]
    },
    {
     "title": "Server - HTTP responses code",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 122 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_server_http_responses_total{proxy=~\"$backend\",server=~\"$server\",code=~\"$code\",instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "{{ code }} {{ proxy }} {{ server }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Front - Number of sessions",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 110 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_frontend_sessions_total{proxy=~\"$frontend\",instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "Total {{ proxy }}"
      },
      {
       "expr": "rate(haproxy_frontend_denied_sessions_total{proxy=~\"$frontend\",instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "Denied {{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Number of sessions",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 110 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_backend_sessions_total{proxy=~\"$backend\",instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "Total {{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Maximum observed number of active sessions and limit",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 123 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_backend_max_sessions{proxy=~\"$backend\",instance=\"proxy:8080\"}",
       "legendFormat": "Max {{ proxy }}"
      },
      {
       "expr": "haproxy_backend_limit_sessions{proxy=~\"$backend\",instance=\"proxy:8080\"}",
       "legendFormat": "Limit {{ proxy }}"
      }
     ]
    },
    {
     "title": "Front - Maximum observed number of active sessions and limit",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 123 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_frontend_max_sessions{proxy=~\"$frontend\",instance=\"proxy:8080\"}",
       "legendFormat": "Max {{ proxy }}"
      },
      {
       "expr": "haproxy_frontend_limit_sessions{proxy=~\"$frontend\",instance=\"proxy:8080\"}",
       "legendFormat": "Limit {{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Maximum observed number of sessions per second",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 136 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_backend_max_session_rate{proxy=~\"$backend\",instance=\"proxy:8080\"}",
       "legendFormat": "Max {{ proxy }}"
      }
     ]
    },
    {
     "title": "Front - Maximum observed number of sessions per second and limit",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 136 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_frontend_max_session_rate{proxy=~\"$frontend\",instance=\"proxy:8080\"}",
       "legendFormat": "Max {{ proxy }}"
      },
      {
       "expr": "haproxy_frontend_limit_session_rate{proxy=~\"$frontend\",instance=\"proxy:8080\"}",
       "legendFormat": "Limit {{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Failed header rewriting warnings",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 149 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_backend_failed_header_rewriting_total{proxy=~\"$frontend\",instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Front - Failed header rewriting warnings",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 149 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_frontend_failed_header_rewriting_total{proxy=~\"$frontend\",instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back -  Last session assigned",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 162 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(haproxy_backend_last_session_seconds{proxy=~\"$frontend\",instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Front - Maximum observed number of HTTP requests per second",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 162 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_frontend_http_requests_rate_max{proxy=~\"$frontend\",instance=\"proxy:8080\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back -  Data transfers aborted",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 175 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(haproxy_backend_client_aborts_total{proxy=~\"$frontend\",instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "By client {{ proxy }}"
      },
      {
       "expr": "rate(haproxy_backend_server_aborts_total{proxy=~\"$frontend\",instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "By server {{ proxy }}"
      }
     ]
    },
    {
     "title": "Server -  Data transfers aborted",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 175 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_server_client_aborts_total{proxy=~\"$frontend\",server=~\"$server\",instance=\"proxy:8080\"}",
       "legendFormat": "By client {{ proxy }} / {{ server }}"
      },
      {
       "expr": "haproxy_server_server_aborts_total{proxy=~\"$frontend\",server=~\"$server\",instance=\"proxy:8080\"}",
       "legendFormat": "By server {{ proxy }} / {{ server }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Health and Weight",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Back - UP->DOWN transitions",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 111 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_backend_check_up_down_total{proxy=~\"$backend\", instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Service weight",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 111 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_backend_weight{proxy=~\"$backend\", instance=\"proxy:8080\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Service user weight",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 125 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_backend_uweight{proxy=~\"$backend\", instance=\"proxy:8080\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cache / Compressor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Front - Cache lookups / hits",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 112 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_frontend_http_cache_lookups_total{proxy=~\"$frontend\", instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "Lookups {{ proxy }} "
      },
      {
       "expr": "rate(haproxy_frontend_http_cache_hits_total{proxy=~\"$frontend\", instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "Hits {{ proxy }} "
      }
     ]
    },
    {
     "title": "Back - Cache lookups / hits",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 112 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_backend_http_cache_lookups_total{proxy=~\"$backend\", instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "Lookups {{ proxy }} "
      },
      {
       "expr": "rate(haproxy_backend_http_cache_hits_total{proxy=~\"$backend\", instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "Hits {{ proxy }} "
      }
     ]
    },
    {
     "title": "Front - Compressor",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 123 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(haproxy_frontend_http_comp_bytes_in_total{proxy=~\"$frontend\", instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "Bytes fed {{ proxy }} "
      },
      {
       "expr": "rate(haproxy_frontend_http_comp_bytes_out_total{proxy=~\"$frontend\", instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "Bytes emitted {{ proxy }} "
      },
      {
       "expr": "rate(haproxy_frontend_http_comp_bytes_bypassed_total{proxy=~\"$backend\", instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "Bytes bypassed  {{ proxy }} "
      }
     ]
    },
    {
     "title": "Back - Compressor",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 123 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(haproxy_backend_http_comp_bytes_in_total{proxy=~\"$backend\", instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "Bytes fed {{ proxy }} "
      },
      {
       "expr": "rate(haproxy_backend_http_comp_bytes_out_total{proxy=~\"$backend\", instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "Bytes emitted {{ proxy }} "
      },
      {
       "expr": "rate(haproxy_backend_http_comp_bytes_bypassed_total{proxy=~\"$backend\", instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "Bytes bypassed  {{ proxy }} "
      }
     ]
    },
    {
     "title": "Front - Responses compressed",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 134 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_frontend_http_comp_responses_total{proxy=~\"$frontend\", instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }} "
      }
     ]
    },
    {
     "title": "Back - Responses compressed",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 134 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_backend_http_comp_responses_total{proxy=~\"$backend\", instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }} "
      }
     ]
    }
   ]
  },
  {
   "title": "Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Front - Status",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 113 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_frontend_status{proxy=~\"$frontend\",instance=\"proxy:8080\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Status",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 113 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_backend_status{proxy=~\"$backend\",instance=\"proxy:8080\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Front - Internal errors",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 124 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_frontend_internal_errors_total{proxy=~\"$backend\",instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Internal errors",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 124 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_backend_internal_errors_total{proxy=~\"$backend\",instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Active servers",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 135 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_backend_active_servers{proxy=~\"$backend\",instance=\"proxy:8080\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Backup servers",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 135 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_backend_backup_servers{proxy=~\"$backend\",instance=\"proxy:8080\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    }
   ]
  },
  {
   "title": "By server - Throughtput  / Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server - Incoming / Outgoing bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 114 },
     "fieldConfig": { "defaults": { "unit": "bits" } },
     "targets": [
      {
       "expr": "rate(haproxy_server_bytes_in_total{proxy=~\"$backend\",server=~\"$server\",instance=\"proxy:8080\"}[$__rate_interval])*8",
       "legendFormat": "IN {{ proxy }} / {{ server }}"
      },
      {
       "expr": "rate(haproxy_server_bytes_out_total{proxy=~\"$backend\",server=~\"$server\",instance=\"proxy:8080\"}[$__rate_interval])*8",
       "legendFormat": "OUT {{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Connections",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 122 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_server_used_connections_current{proxy=~\"$backend\",server=~\"$server\",instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "In use {{ proxy }} / {{ server }}{{ proxy }}"
      },
      {
       "expr": "rate(haproxy_server_idle_connections_current{proxy=~\"$backend\",server=~\"$server\",instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "Estimated {{ proxy }} / {{ server }}{{ proxy }}"
      }
     ]
    },
    {
     "title": "Server - Connections attempts / error",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 131 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_server_connection_attempts_total{proxy=~\"$backend\",server=~\"$server\",instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "Attempts {{ proxy }} / {{ server }}"
      },
      {
       "expr": "rate(haproxy_server_connection_errors_total{proxy=~\"$backend\",server=~\"$server\",instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "Error {{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Number of connections reuses",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 139 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_server_connection_reuses_total{proxy=~\"$backend\",server=~\"$server\",instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "Reuses {{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Idle connections",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 148 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_server_idle_connections_current{proxy=~\"$backend\",server=~\"$server\",instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "Available idle connections {{ proxy }} / {{ server }}"
      },
      {
       "expr": "rate(haproxy_server_idle_connections_limit{proxy=~\"$backend\",server=~\"$server\",instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "Limit available idle connections {{ proxy }} / {{ server }}{{ proxy }}"
      },
      {
       "expr": "rate(haproxy_server_safe_idle_connections_current{proxy=~\"$backend\",server=~\"$server\",instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "Number of safe idle connections {{ proxy }} / {{ server }}{{ proxy }}"
      },
      {
       "expr": "rate(haproxy_server_unsafe_idle_connections_current{proxy=~\"$backend\",server=~\"$server\",instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "Number of unsafe idle connections {{ proxy }} / {{ server }}{{ proxy }}"
      }
     ]
    }
   ]
  },
  {
   "title": "By server - Requests / Responses / Queues",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server - HTTP responses denied",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 115 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_server_responses_denied_total{proxy=~\"$backend\", instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "Denied {{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Error / Redispatch / Retry",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 124 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_server_redispatch_warnings_total{proxy=~\"$backend\",server=~\"$server\",instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "Redispatch {{ proxy }} / {{ server }}"
      },
      {
       "expr": "rate(haproxy_server_retry_warnings_total{proxy=~\"$backend\",server=~\"$server\",instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "Retry {{ proxy }} / {{ server }}"
      },
      {
       "expr": "rate(haproxy_server_response_errors_total{proxy=~\"$backend\",server=~\"$server\",instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "Error {{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Queued requests",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 131 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_server_current_queue{proxy=~\"$backend\",server=~\"$server\",instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "Current {{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Max  queued requests and limit",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 138 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_server_max_queue{proxy=~\"$backend\",server=~\"$server\",instance=\"proxy:8080\"}",
       "legendFormat": "Max {{ proxy }} / {{ server }}"
      },
      {
       "expr": "haproxy_server_queue_limit{proxy=~\"$backend\",server=~\"$server\",instance=\"proxy:8080\"}",
       "legendFormat": "Limit {{ proxy }} / {{ server }}"
      }
     ]
    }
   ]
  },
  {
   "title": "By server - Times",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server - Average connection time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 116 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "haproxy_server_connect_time_average_seconds{proxy=~\"$backend\",server=~\"$server\",instance=\"proxy:8080\"}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Max connection time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 123 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "haproxy_server_max_connect_time_seconds{proxy=~\"$backend\",server=~\"$server\",instance=\"proxy:8080\"}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Average response time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 130 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "haproxy_server_response_time_average_seconds{proxy=~\"$backend\",server=~\"$server\",instance=\"proxy:8080\"}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Max response time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 137 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "haproxy_server_max_response_time_seconds{proxy=~\"$backend\",server=~\"$server\",instance=\"proxy:8080\"}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Average total time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 144 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "haproxy_server_total_time_average_seconds{proxy=~\"$backend\",server=~\"$server\",instance=\"proxy:8080\"}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Max total time",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 152 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "haproxy_server_max_total_time_seconds{proxy=~\"$backend\",server=~\"$server\",instance=\"proxy:8080\"}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Average queue time for last 1024 successful connections",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 161 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(haproxy_server_queue_time_average_seconds{proxy=~\"$backend\",server=~\"$server\",instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Max queue time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 170 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(haproxy_server_max_queue_time_seconds{proxy=~\"$backend\",server=~\"$server\",instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    }
   ]
  },
  {
   "title": "By server - Sessions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server - Number of active sessions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 117 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_server_sessions_total{proxy=~\"$backend\",server=~\"$server\",instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "Total {{ proxy }} / {{ server }}"
      },
      {
       "expr": "haproxy_server_limit_sessions{proxy=~\"$backend\",instance=\"proxy:8080\"}",
       "legendFormat": "Limit {{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Failed header rewriting warnings",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 125 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_server_failed_header_rewriting_total{proxy=~\"$frontend\",server=~\"$server\",instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }} /  {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Number of sessions per second and limit",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 134 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_server_max_session_rate{proxy=~\"$backend\",server=~\"$server\",instance=\"proxy:8080\"}",
       "legendFormat": "Rate {{ proxy }} / {{ server }}"
      },
      {
       "expr": "haproxy_server_limit_session_rate{proxy=~\"$backend\",server=~\"$server\",instance=\"proxy:8080\"}",
       "legendFormat": "Limit {{ proxy }} / {{ server }}"
      }
     ]
    }
   ]
  },
  {
   "title": "By server - Health and Weight",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server - Service weight",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 118 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "haproxy_server_weight{proxy=~\"$backend\",server=~\"$server\",instance=\"proxy:8080\"}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Users weight",
     "type": "timeseries",
     "description": "Server's user weight, or sum of active servers' user weights for a backend",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 126 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "haproxy_server_uweight{proxy=~\"$backend\",instance=\"proxy:8080\"}",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Server - UP->DOWN transitions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 134 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(haproxy_server_check_up_down_total{proxy=~\"$backend\",server=~\"$server\",instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Checks failures",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 142 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(haproxy_server_check_failures_total{proxy=~\"$backend\",server=~\"$server\",instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Checks duration",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 153 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "haproxy_server_check_duration_seconds{proxy=~\"$backend\",server=~\"$server\",instance=\"proxy:8080\"}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server -Throttle percentage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 164 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "haproxy_server_current_throttle{proxy=~\"$backend\",server=~\"$server\",instance=\"proxy:8080\"}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Number of seconds since last session assigned to server/backend",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 174 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(haproxy_server_last_session_seconds{proxy=~\"$backend\", server=~\"$server\",instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    }
   ]
  },
  {
   "title": "By server - Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server - Status",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 119 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_server_status{proxy=~\"$backend\",server=~\"$server\",instance=\"proxy:8080\"}",
       "legendFormat": "{{ proxy }} / {{ server }}"
      }
     ]
    },
    {
     "title": "Server - Internal errors",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 127 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_server_internal_errors_total{proxy=~\"$backend\",instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Server - Failed DNS resolutions",
     "type": "timeseries",
     "description": "Number of failed DNS resolutions in current worker process since started",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 134 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_process_failed_resolutions{instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "Failed"
      }
     ]
    }
   ]
  },
  {
   "title": "Process Connections / Sessions / Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process - Sessions over last second",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 120 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_process_current_session_rate{instance=\"proxy:8080\"}",
       "legendFormat": "Current number of sessions per second over last elapsed second"
      },
      {
       "expr": "haproxy_process_limit_session_rate{instance=\"proxy:8080\"}",
       "legendFormat": "Configured maximum number of sessions per second"
      }
     ]
    },
    {
     "title": "Process - Total sessions / requests",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 120 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_process_connections_total{instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "Total number of created sessions"
      },
      {
       "expr": "rate(haproxy_process_requests_total{instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "Total number of requests (TCP or HTTP)"
      }
     ]
    },
    {
     "title": "Process - Connections over last second",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 134 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_process_current_connection_rate{instance=\"proxy:8080\"}",
       "legendFormat": "Current number of connections per second over last elapsed second"
      },
      {
       "expr": "haproxy_process_limit_connection_rate{instance=\"proxy:8080\"}",
       "legendFormat": "Configured maximum number of connections per second."
      }
     ]
    },
    {
     "title": "Process - Max connections",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 134 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_process_max_connections{instance=\"proxy:8080\"}",
       "legendFormat": "Maximum number of concurrent connections"
      },
      {
       "expr": "haproxy_process_hard_max_connections{instance=\"proxy:8080\"}",
       "legendFormat": "Initial Maximum number of concurrent connections"
      }
     ]
    }
   ]
  },
  {
   "title": "Process Compression",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process - Compression memory",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 121 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_process_current_zlib_memory{instance=\"proxy:8080\"}",
       "legendFormat": "Current memory used for zlib in bytes"
      },
      {
       "expr": "haproxy_process_max_zlib_memory{instance=\"proxy:8080\"}",
       "legendFormat": "Configured maximum amount of memory for zlib in bytes"
      }
     ]
    },
    {
     "title": "Process - Compression",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 121 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_process_http_comp_bytes_in_total{instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "Number of bytes per second over last elapsed second, before http compression"
      },
      {
       "expr": "rate(haproxy_process_http_comp_bytes_out_total{instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "Number of bytes per second over last elapsed second, after http compression"
      },
      {
       "expr": "haproxy_process_limit_http_comp{instance=\"proxy:8080\"}",
       "legendFormat": "Configured maximum input compression rate in bytes"
      }
     ]
    }
   ]
  },
  {
   "title": "Process SSL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process - SSL cache",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 122 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_process_ssl_cache_lookups_total{instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "Total number of SSL session cache lookups"
      },
      {
       "expr": "rate(haproxy_process_ssl_cache_misses_total{instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "Total number of SSL session cache misses"
      }
     ]
    },
    {
     "title": "Process - SSL key rate",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 122 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_process_current_frontend_ssl_key_rate{instance=\"proxy:8080\"}",
       "legendFormat": "Current frontend SSL Key computation per second over last elapsed second"
      },
      {
       "expr": "haproxy_process_current_backend_ssl_key_rate{instance=\"proxy:8080\"}",
       "legendFormat": "Current backend SSL Key computation per second over last elapsed second"
      }
     ]
    },
    {
     "title": "Process - SSL rate",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 134 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_process_current_ssl_rate{instance=\"proxy:8080\"}",
       "legendFormat": "Current number of SSL sessions per second over last elapsed second"
      },
      {
       "expr": "haproxy_process_limit_ssl_rate{instance=\"proxy:8080\"}",
       "legendFormat": "Configured maximum number of SSL sessions per second"
      }
     ]
    },
    {
     "title": "Process - SSL connections",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 134 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_process_current_ssl_connections{instance=\"proxy:8080\"}",
       "legendFormat": "Current number of opened SSL connections"
      },
      {
       "expr": "haproxy_process_max_ssl_connections{instance=\"proxy:8080\"}",
       "legendFormat": "Configured maximum number of concurrent SSL connections"
      }
     ]
    },
    {
     "title": "Process - SSL reuse ratio",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 146 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "haproxy_process_frontend_ssl_reuse{instance=\"proxy:8080\"}",
       "legendFormat": "SSL session reuse ratio (percent)"
      }
     ]
    }
   ]
  },
  {
   "title": "Process Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process - Memory",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 123 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "haproxy_process_max_memory_bytes{instance=\"proxy:8080\"}",
       "legendFormat": "Per-process memory limit (in bytes); 0=unset"
      },
      {
       "expr": "rate(haproxy_process_pool_allocated_bytes{instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "Total amount of memory allocated in pools (in bytes)"
      },
      {
       "expr": "rate(haproxy_process_pool_used_bytes{instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "Total amount of memory used in pools (in bytes)"
      }
     ]
    },
    {
     "title": "Process - Tasks",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 123 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_process_current_tasks{instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "Current number of tasks"
      },
      {
       "expr": "haproxy_process_current_run_queue{instance=\"proxy:8080\"}",
       "legendFormat": "Current number of tasks in the run-queue"
      },
      {
       "expr": "haproxy_process_stopping{instance=\"proxy:8080\"}",
       "legendFormat": "Non zero means stopping in progress"
      }
     ]
    },
    {
     "title": "Process - Maximum open files / sockets",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 136 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_process_max_fds{instance=\"proxy:8080\"}",
       "legendFormat": "Maximum number of open file descriptors; 0=unset"
      },
      {
       "expr": "haproxy_process_max_sockets{instance=\"proxy:8080\"}",
       "legendFormat": "Maximum number of open sockets"
      }
     ]
    },
    {
     "title": "Process - Pipes",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 136 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_process_max_pipes{instance=\"proxy:8080\"}",
       "legendFormat": "Configured maximum number of pipes"
      },
      {
       "expr": "rate(haproxy_process_pipes_used_total{instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "Number of pipes in used"
      },
      {
       "expr": "rate(haproxy_process_pipes_free_total{instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "Number of pipes unused"
      }
     ]
    },
    {
     "title": "Process - Configured threads / processes",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 149 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_process_nbthread{instance=\"proxy:8080\"}",
       "legendFormat": "Threads"
      },
      {
       "expr": "haproxy_process_nbproc{instance=\"proxy:8080\"}",
       "legendFormat": "Processes"
      }
     ]
    },
    {
     "title": "Process - Pool allocations",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 149 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_process_pool_failures_total{instance=\"proxy:8080\"}",
       "legendFormat": "Total number of failed pool allocations"
      }
     ]
    },
    {
     "title": "Process - Idle",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 162 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "haproxy_process_idle_time_percent{instance=\"proxy:8080\"}",
       "legendFormat": "Idle to total ratio over last sample (percent)"
      }
     ]
    },
    {
     "title": "Process - Jobs",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 162 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(haproxy_process_jobs{instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "Current number of active jobs (listeners, sessions, open devices)"
      },
      {
       "expr": "rate(haproxy_process_unstoppable_jobs{instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "Current number of active jobs that can't be stopped during a soft stop"
      },
      {
       "expr": "rate(haproxy_process_listeners{instance=\"proxy:8080\"}[$__rate_interval])",
       "legendFormat": "Current number of active listeners"
      }
     ]
    },
    {
     "title": "Process - Peers",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 175 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_process_active_peers{instance=\"proxy:8080\"}",
       "legendFormat": "Current number of active peers"
      },
      {
       "expr": "haproxy_process_connected_peers{instance=\"proxy:8080\"}",
       "legendFormat": "Current number of connected peers"
      }
     ]
    },
    {
     "title": "Process - Logs",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 175 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "haproxy_process_dropped_logs_total{instance=\"proxy:8080\"}",
       "legendFormat": "Total number of dropped logs"
      },
      {
       "expr": "haproxy_process_recv_logs_total{instance=\"proxy:8080\"}",
       "legendFormat": "Total number of log messages received by log-forwarding listeners"
      }
     ]
    },
    {
     "title": "Process - Bytes out",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 188 },
     "fieldConfig": { "defaults": { "unit": "bits" } },
     "targets": [
      {
       "expr": "rate(haproxy_process_bytes_out_total{instance=\"proxy:8080\"}[$__rate_interval])*8",
       "legendFormat": "Emitted by current worker {{ proxy }}"
      },
      {
       "expr": "rate(haproxy_process_spliced_bytes_out_total{instance=\"proxy:8080\"}[$__rate_interval])*8",
       "legendFormat": "Emitted by current worker through a kernel pipe {{ proxy }}"
      }
     ]
    },
    {
     "title": "Process - Uptime",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 188 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "haproxy_process_uptime_seconds{instance=\"proxy:8080\"}",
       "legendFormat": "How long ago this worker process was started"
      }
     ]
    }
   ]
  }
 ]
}