[package]
name = "telegram"
version = "0.1.0"
authors = ["Kirill Udaltsov <commits@udaltsovk.ru>"]
license.workspace = true
edition.workspace = true

[lib]
name = "telegram"
path = "./src/lib.rs"

[[bin]]
name = "minizord-telegram"
path = "./src/main.rs"

[dependencies]
