[package]
name = "macros"
version = "0.1.0"
authors = ["Kirill Udaltsov <commits@udaltsovk.ru>"]
license.workspace = true
edition.workspace = true

[dependencies]
proc-macros = { path = "proc" }

pastey = "0.1"

async-trait = "0.1"
tracing.workspace = true

[lints]
workspace = true

