[package]
name = "handler"
version = "0.1.0"
edition = "2024"
authors = ["Kirill Udaltsov <commits@udaltsovk.ru>"]

[dependencies]
macros.workspace = true
utils.workspace = true
dto.workspace = true

service = { path = "../service" }

thiserror.workspace = true
log.workspace = true

serde.workspace = true
serde_json.workspace = true
strum.workspace = true
strum_macros.workspace = true

validator.workspace = true

ulid.workspace = true

tracing.workspace = true

utoipa.workspace = true
utoipa-actix-web.workspace = true

actix-web.workspace = true
actix-web-lab.workspace = true
actix-web-validation.workspace = true
