[package]
name = "handler"
version = "0.1.0"
edition = "2024"
authors = ["Kirill Udaltsov <commits@udaltsovk.ru>"]

[dependencies]
macros.workspace = true
utils.workspace = true
dto.workspace = true

service.path = "../service"

thiserror.workspace = true

serde.workspace = true
validator.workspace = true

ulid.workspace = true

tracing.workspace = true

utoipa.workspace = true
utoipa-actix-web.workspace = true

actix-web.workspace = true
actix-web-lab.workspace = true
