target: all

multitenancy_enabled: false

common:
  storage:
    backend: s3
    s3:
      bucket_name: mimir
      endpoint: s3:9000
      access_key_id: ${S3_ACCESS_KEY}
      secret_access_key: ${S3_SECRET_KEY}
      insecure: true

blocks_storage:
  storage_prefix: blocks

server:
  http_listen_port: 9009
  log_level: warn

ingester:
  ring:
    replication_factor: 1
