global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'minizord-api-scrap'
    metrics_path: /metrics
    static_configs:
      - targets: ['api:8080']
  - job_name: 'loki'
    metrics_path: /metrics
    static_configs:
      - targets: ['loki:3100']
  - job_name: 'tempo'
    metrics_path: /metrics
    static_configs:
      - targets: ['tempo:3200']
  - job_name: 'proxy'
    metrics_path: /metrics
    static_configs:
      - targets: ['proxy:8080']


remote_write:
  - url: "http://mimir:9009/api/v1/push"
    remote_timeout: 30s
    write_relabel_configs:
      - source_labels: [__name__]
        regex: ".*"
        action: keep
