minizord:
  platform-url: http://localhost:8080
  mail-address: noreply@minizord.test

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/minizord-mail
    username: postgres
    password: postgres
  liquibase:
    enabled: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: localhost
    port: 1025
    username: mailhog
    password: mailhog
    test-connection: true
  output:
    ansi:
      enabled: always

otel:
  exporter:
    otlp:
      endpoint: http://localhost:4317
      protocol: grpc

logging:
  config: classpath:logback/dev.xml
