[package]
name = "api"
version = "0.1.0"
edition = "2024"
authors = ["Kirill Udaltsov <commits@udaltsovk.ru>"]

[dependencies]
env-vars-config.workspace = true
dto.workspace = true

repository.path = "./repository"
service.path = "./service"
handler.path = "./handler"

env_logger.workspace = true
log.workspace = true

utoipa.workspace = true
utoipa-swagger-ui = { version = "9.0", features = ["actix-web", "vendored"] }

actix-web.workspace = true
actix-rt = "2.10"
actix-cors = "0.7"
# actix-files = "0.6"
actix-web-lab.workspace = true
actix-contrib-logger = "0.1"
actix-multipart = "0.7"

utoipa-actix-web.workspace = true
