[package]
name = "mail"
version = "0.1.0"
authors = ["Kirill Udaltsov <commits@udaltsovk.ru>"]
license.workspace = true
edition.workspace = true

[lib]
name = "mail"
path = "./src/lib.rs"

[[bin]]
name = "minizord-mail"
path = "./src/main.rs"

[dependencies]

[lints]
workspace = true

