[package]
name = "repository"
version = "0.1.0"
edition = "2024"
authors = ["Kirill Udaltsov <commits@udaltsovk.ru>"]

[features]
default = ["surrealdb", "s3"]
surrealdb = ["dep:surrealdb", "dep:surrealdb-migrations", "dep:include_dir"]
s3 = ["dep:aws-sdk-s3", "dep:infer", "dep:mime_guess"]

[dependencies]
macros.workspace = true

thiserror.workspace = true
#log.workspace = true

serde.workspace = true
strum.workspace = true
strum_macros.workspace = true

chrono.workspace = true
ulid.workspace = true

bytes.workspace = true

tracing.workspace = true

surrealdb = { workspace = true, optional = true }
surrealdb-migrations = { version = "2.2", optional = true }
include_dir = { version = "0.7", optional = true }

aws-sdk-s3 = { workspace = true, optional = true }
infer = { version = "0.19", optional = true }
mime_guess = { version = "2.0", optional = true }
