[package]
name = "repository"
version = "0.1.0"
edition = "2024"
authors = ["Kirill Udaltsov <commits@udaltsovk.ru>"]

[features]
default = ["surrealdb"]
surrealdb = ["dep:surrealdb", "surrealdb-migrations", "include_dir"]

[dependencies]
macros.workspace = true

thiserror.workspace = true

serde.workspace = true
strum.workspace = true
strum_macros.workspace = true

chrono.workspace = true
ulid.workspace = true

tracing.workspace = true

surrealdb = { workspace = true, optional = true }
surrealdb-migrations = { version = "2.2", optional = true }
include_dir = { version = "0.7", optional = true }
