name: Backend CI

on:
  push:
    paths:
      - .github/workflows/backend-ci.yml
      - backend/**
    branches: 
      - master
  pull_request:
    paths:
      - backend/**
    branches:
      - master
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Rust
        uses: actions/checkout@master
      - name: Install cargo-audit
        run: cargo install cargo-audit
      - name: Build
        run: cd ./backend && cargo build --all
      - name: Test
        run: cd ./backend && cargo test --all
      - name: Clippy
        run: cd ./backend && cargo clippy -- -D warnings
      - name: Audit
        run: cd ./backend && cargo audit
