name: Backend CI

on:
  push:
    paths:
      - .github/workflows/backend-ci.yml
      - backend/**
    branches: 
      - master
  pull_request:
    paths:
      - backend/**
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [stable, nightly, macos, win64]
        include:
          - build: stable
            os: ubuntu-latest
            rust: stable
          - build: nightly
            os: ubuntu-latest
            rust: nightly
          - build: macos
            os: macos-latest
            rust: stable
          - build: win64
            os: windows-latest
            rust: stable-x86_64-pc-windows-msvc
    steps:
    - uses: actions/checkout@master
    - name: Install Rust
      run: |
        rustup update ${{ matrix.rust }} --no-self-update
        rustup default ${{ matrix.rust }}
    - name: Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Run tests
      run: |
        cd ./backend 
        cargo test --all
  format:
    name: Format code using Rustfmt
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@master
    - name: Install Rust
      run: |
        rustup update nightly --no-self-update
        rustup default nightly
        rustup component add rustfmt
    - name: Run Rustfmt
      run: |
        cd ./backend 
        cargo fmt --all -- --check
  lint:
    name: Lint using Clippy
    runs-on: ubuntu-latest
    needs: format
    steps:
    - uses: actions/checkout@master
    - name: Install Rust
      run: |
        rustup update nightly --no-self-update
        rustup default nightly
        rustup component add clippy
    - name: Run Clippy
      run: |
        cd ./backend
        cargo clippy --all -- -D warnings
  audit:
    name: Audit using cargo-audit
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - uses: actions/checkout@master
    - name: Install Rust
      run: |
        rustup update nightly --no-self-update
        rustup default nightly
    - name: Install cargo-audit
      run: cargo install cargo-audit
    - name: Run cargo-audit
      run: |
        cd ./backend 
        cargo audit
